### ISSUE TITLE
2016-12-27 TOPS pcap fails to parse (msg_type=0)

### ISSUE THREAD

**Issue by aprsa** [vfrazao-ns1/IEXTools#9]
While parsing IEX pcap for 2016-12-27, IEXTools fails with:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IEXTools/messages.py", line 133, in decode_message
    fmt = self.DECODE_FMT[msg_type]
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./iexdl.py", line 46, in <module>
    for message in iex_log:
  File "/usr/local/lib/python3.7/dist-packages/IEXTools/IEXparser.py", line 123, in __next__
    return self.get_next_message()
  File "/usr/local/lib/python3.7/dist-packages/IEXTools/IEXparser.py", line 268, in get_next_message
    self.message_type, self.message_binary
  File "/usr/local/lib/python3.7/dist-packages/IEXTools/messages.py", line 135, in decode_message
    raise ProtocolException(f"Unknown message type: {e.args}")
IEXTools.IEXHISTExceptions.ProtocolException: Unknown message type: (0,)
```

I haven't looked into TOPS specification on what 0 is, if it is specified at all, but either way, it raises an exception at start that prevents any subsequent data to be parsed.

**Comment by vfrazao-ns1** [comment]
Hey @aprsa, thanks for making an issue. I will take a look and try to reproduce this weekend.

**Comment by MurattuW** [comment]
@aprsa I think you could try my fix on #10 :)
